# Generated by Django 3.0.4 on 2020-03-21 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20200319_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfcertificationquestion',
            name='language',
            field=models.ForeignKey(default='en', on_delete=django.db.models.deletion.PROTECT, to='clinic.Language', to_field='ietf_tag'),
        ),
    ]
